liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database/cityescape-master.xml
    check-change-log-location: true

---

spring:
  profiles: 'local'

  datasource:
    url: jdbc:mysql://localhost:3306/city_escape
    username: cityescape
    password: cityescape