liquibase:
    enabled: false
    drop-first: false
    change-log: classpath:database/com.cityescape-master.xml
    check-change-log-location: true

spring:
  data:
    solr:
      host: http://192.168.0.5:8983/solr

---

spring:
  profiles: 'local'

  datasource:
    url: jdbc:mysql://localhost:3306/city_escape
    username: cityescape
    password: cityescape